/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    InfiniteScroll: typeof import('./components/common/InfiniteScroll.vue')['default']
    JrnwnLogo: typeof import('./components/JrnwnLogo.vue')['default']
    NotificationArea: typeof import('./components/common/NotificationArea.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TimeoutBar: typeof import('./components/common/TimeoutBar.vue')['default']
  }
}
